# Config yaml for the experiments

dir: ./data/fr2_desk/  # always end the path with "/"

prior_sigma: [0.01, 1e-4] # angle and distance in meter
odom_sigma: [2, 0.01]
bbox_sigma: 5

add_landmarks: True
add_odom_noise: False
add_measurement_noise: False