# Config yaml for the experiments

dir: ./data/fr3_office/ # always end the path with "/"

prior_sigma: [0.01, 1e-4] # angle and distance in meter
odom_sigma: [0.5, 0.01]
bbox_sigma: 5

add_landmarks: True
add_odom_noise: True
add_measurement_noise: False
